In [1]:
import pandas as pd
from datetime import datetime

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

## Get Risk Free rates from daily treasury rates

In [2]:
treasury_rates = pd.read_csv('daily-treasury-rates.csv', index_col='Date')
treasury_rates

,1 Mo,2 Mo,3 Mo,4 Mo,6 Mo,1 Yr,2 Yr,3 Yr,5 Yr,7 Yr,10 Yr,20 Yr,30 Yr
Date,,,,,,,,,,,,,
09/30/2024,4.93,4.87,4.73,4.65,4.38,3.98,3.66,3.58,3.58,3.67,3.81,4.19,4.14
09/27/2024,4.90,4.87,4.68,4.64,4.35,3.90,3.55,3.49,3.50,3.60,3.75,4.15,4.10
09/26/2024,4.90,4.87,4.68,4.65,4.38,3.96,3.60,3.54,3.55,3.65,3.79,4.17,4.12
09/25/2024,4.79,4.78,4.69,4.64,4.36,3.89,3.53,3.49,3.52,3.65,3.79,4.18,4.14
09/24/2024,4.78,4.78,4.69,4.63,4.36,3.88,3.49,3.44,3.47,3.60,3.74,4.13,4.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1/8/2024,5.54,5.48,5.49,5.39,5.24,4.82,4.36,4.11,3.97,3.99,4.01,4.33,4.17
1/5/2024,5.54,5.48,5.47,5.41,5.24,4.84,4.40,4.17,4.02,4.04,4.05,4.37,4.21
1/4/2024,5.56,5.48,5.48,5.41,5.25,4.85,4.38,4.14,3.97,3.99,3.99,4.30,4.13
1/3/2024,5.54,5.54,5.48,5.41,5.25,4.81,4.33,4.07,3.90,3.92,3.91,4.21,4.05
1/2/2024,5.55,5.54,5.46,5.41,5.24,4.80,4.33,4.09,3.93,3.95,3.95,4.25,4.08

In [3]:
#selected_dates = treasury_rates.loc[['07/26/2024','08/30/2024','09/27/2024']]
selected_dates = treasury_rates.loc[['09/30/2024']]
selected_dates

,1 Mo,2 Mo,3 Mo,4 Mo,6 Mo,1 Yr,2 Yr,3 Yr,5 Yr,7 Yr,10 Yr,20 Yr,30 Yr
Date,,,,,,,,,,,,,
09/30/2024,4.93,4.87,4.73,4.65,4.38,3.98,3.66,3.58,3.58,3.67,3.81,4.19,4.14

In [4]:
df4 = pd.read_csv('data/SPX/UnderlyingOptionsIntervals_3600sec_calcs_oi_2024-10-11.csv')
df5 = pd.read_csv('data/SPX/UnderlyingOptionsIntervals_3600sec_calcs_oi_2024-10-18.csv')
df6 = pd.read_csv('data/SPX/UnderlyingOptionsIntervals_3600sec_calcs_oi_2024-10-25.csv')

In [5]:
df4.head()

,underlying_symbol,quote_datetime,root,expiration,strike,option_type,open,high,low,close,...,underlying_ask,implied_underlying_price,active_underlying_price,implied_volatility,delta,gamma,theta,vega,rho,open_interest
0,^SPX,2024-10-11 10:30:00,SPX,2024-10-18,200.0,C,0.0,0.0,0.0,0.0,...,5818.81,0.0,5817.085,7.9956,0.9996,0.0,0.0,0.0044,-0.1472,47
1,^SPX,2024-10-11 11:30:00,SPX,2024-10-18,200.0,C,0.0,0.0,0.0,0.0,...,5812.14,0.0,5810.855,5.7544,0.9998,0.0,0.0,0.0000,-0.1536,47
2,^SPX,2024-10-11 12:30:00,SPX,2024-10-18,200.0,C,0.0,0.0,0.0,0.0,...,5808.35,0.0,5807.075,8.3802,0.9996,0.0,0.0,0.0066,-0.1589,47
3,^SPX,2024-10-11 13:30:00,SPX,2024-10-18,200.0,C,0.0,0.0,0.0,0.0,...,5808.95,0.0,5807.760,0.0000,0.0000,0.0,0.0,0.0000,0.0000,47
4,^SPX,2024-10-11 14:30:00,SPX,2024-10-18,200.0,C,0.0,0.0,0.0,0.0,...,5814.88,0.0,5813.830,0.0000,0.0000,0.0,0.0,0.0000,0.0000,47

In [6]:
def days_between_dates(date_str1, date_str2):
    # Convert strings to datetime objects
    date1 = datetime.strptime(date_str1, "%Y-%m-%d")
    date2 = datetime.strptime(date_str2, "%Y-%m-%d")
    
    # Calculate the difference in days
    delta = abs((date2 - date1).days)
    
    return delta

In [7]:
def get_period(days):
    if days <= 30:
        return "1 Mo"
    elif days <= 60:
        return "2 Mo"
    elif days <= 90:
        return "3 Mo"
    elif days <= 120:
        return "4 Mo"
    elif days <= 180:
        return "6 Mo"
    elif days <= 365:
        return "1 Yr"
    elif days <= 730:
        return "2 Yr"
    elif days <= 1095:
        return "3 Yr"
    elif days <= 1825:
        return "5 Yr"
    elif days <= 2555:
        return "7 Yr"
    else:
        return "10 Yr"

## For Each Df, add rf_rate, time to maturity (days / 252), option prices (mid point of ask and bid)

In [8]:
df1_date = "2024-10-11"
treasury_rate_date = "09/30/2024"

rf_rates = []
time_to_maturity = []
option_prices = []

for index, row in df4.iterrows():
    expiration = row['expiration']
    maturity = days_between_dates(df1_date,expiration)
    time_to_maturity.append(maturity/252) #time to maturity in days/year
    rf_rate_period = get_period(maturity)
    rf_rates.append(selected_dates.loc[treasury_rate_date,rf_rate_period])
    option_price = (row['ask'] + row['bid'])/2
    option_prices.append(option_price)

In [9]:
df4['risk_free_rate'] = rf_rates

In [10]:
df4['time_to_maturity'] = time_to_maturity

In [11]:
df4['option_price'] = option_prices

In [12]:
df4.head()

,underlying_symbol,quote_datetime,root,expiration,strike,option_type,open,high,low,close,...,implied_volatility,delta,gamma,theta,vega,rho,open_interest,risk_free_rate,time_to_maturity,option_price
0,^SPX,2024-10-11 10:30:00,SPX,2024-10-18,200.0,C,0.0,0.0,0.0,0.0,...,7.9956,0.9996,0.0,0.0,0.0044,-0.1472,47,4.93,0.027778,5615.70
1,^SPX,2024-10-11 11:30:00,SPX,2024-10-18,200.0,C,0.0,0.0,0.0,0.0,...,5.7544,0.9998,0.0,0.0,0.0000,-0.1536,47,4.93,0.027778,5609.70
2,^SPX,2024-10-11 12:30:00,SPX,2024-10-18,200.0,C,0.0,0.0,0.0,0.0,...,8.3802,0.9996,0.0,0.0,0.0066,-0.1589,47,4.93,0.027778,5605.25
3,^SPX,2024-10-11 13:30:00,SPX,2024-10-18,200.0,C,0.0,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0000,0.0000,47,4.93,0.027778,5605.20
4,^SPX,2024-10-11 14:30:00,SPX,2024-10-18,200.0,C,0.0,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0000,0.0000,47,4.93,0.027778,5613.00

In [13]:
df2_date = "2024-10-18"
treasury_rate_date = "09/30/2024"

rf_rates = []
time_to_maturity = []
option_prices = []

for index, row in df5.iterrows():
    expiration = row['expiration']
    maturity = days_between_dates(df2_date,expiration)
    time_to_maturity.append(maturity/252) #time to maturity in days/year
    rf_rate_period = get_period(maturity)
    rf_rates.append(selected_dates.loc[treasury_rate_date,rf_rate_period])
    option_price = (row['ask'] + row['bid'])/2
    option_prices.append(option_price)

In [14]:
df5['risk_free_rate'] = rf_rates

In [15]:
df5['time_to_maturity'] = time_to_maturity

In [16]:
df5['option_price'] = option_prices

In [17]:
df5.tail()

,underlying_symbol,quote_datetime,root,expiration,strike,option_type,open,high,low,close,...,implied_volatility,delta,gamma,theta,vega,rho,open_interest,risk_free_rate,time_to_maturity,option_price
168723,^SPX,2024-10-18 12:30:00,SPXW,2025-09-30,7800.0,P,0.0,0.0,0.0,0.0,...,0.1281,-0.9792,0.0001,0.0,3.9423,-70.0919,1,3.98,1.376984,1666.40
168724,^SPX,2024-10-18 13:30:00,SPXW,2025-09-30,7800.0,P,0.0,0.0,0.0,0.0,...,0.1271,-0.9799,0.0001,0.0,3.8722,-70.1249,1,3.98,1.376984,1661.05
168725,^SPX,2024-10-18 14:30:00,SPXW,2025-09-30,7800.0,P,0.0,0.0,0.0,0.0,...,0.1286,-0.9778,0.0001,0.0,4.1052,-70.0087,1,3.98,1.376984,1656.75
168726,^SPX,2024-10-18 15:30:00,SPXW,2025-09-30,7800.0,P,0.0,0.0,0.0,0.0,...,0.1253,-0.9817,0.0001,0.0,3.6536,-70.2128,1,3.98,1.376984,1663.70
168727,^SPX,2024-10-18 16:15:00,SPXW,2025-09-30,7800.0,P,0.0,0.0,0.0,0.0,...,0.1232,-0.9835,0.0001,0.0,3.4392,-70.3009,1,3.98,1.376984,1661.00

In [18]:
df3_date = "2024-10-25"
treasury_rate_date = "09/30/2024"

rf_rates = []
time_to_maturity = []
option_prices = []

for index, row in df6.iterrows():
    expiration = row['expiration']
    maturity = days_between_dates(df3_date,expiration)
    time_to_maturity.append(maturity/252) #time to maturity in days/year
    rf_rate_period = get_period(maturity)
    rf_rates.append(selected_dates.loc[treasury_rate_date,rf_rate_period])
    option_price = (row['ask'] + row['bid'])/2
    option_prices.append(option_price)

In [19]:
df6['risk_free_rate'] = rf_rates

In [20]:
df6['time_to_maturity'] = time_to_maturity

In [21]:
df6['option_price'] = option_prices

In [22]:
df6.head()

,underlying_symbol,quote_datetime,root,expiration,strike,option_type,open,high,low,close,...,implied_volatility,delta,gamma,theta,vega,rho,open_interest,risk_free_rate,time_to_maturity,option_price
0,^SPX,2024-10-25 10:30:00,SPX,2024-11-15,200.0,C,0.0,0.0,0.0,0.0,...,6.6097,0.9986,0.0,-0.3691,0.0774,-0.0114,16,4.93,0.083333,5656.45
1,^SPX,2024-10-25 11:30:00,SPX,2024-11-15,200.0,C,0.0,0.0,0.0,0.0,...,5.7693,0.9995,0.0,0.0000,0.0406,-0.0119,16,4.93,0.083333,5642.75
2,^SPX,2024-10-25 12:30:00,SPX,2024-11-15,200.0,C,0.0,0.0,0.0,0.0,...,6.5611,0.9986,0.0,-0.3244,0.0744,-0.0257,16,4.93,0.083333,5641.50
3,^SPX,2024-10-25 13:30:00,SPX,2024-11-15,200.0,C,0.0,0.0,0.0,0.0,...,5.5490,0.9996,0.0,0.0000,0.0321,-0.0237,16,4.93,0.083333,5622.65
4,^SPX,2024-10-25 14:30:00,SPX,2024-11-15,200.0,C,0.0,0.0,0.0,0.0,...,4.9874,1.0000,0.0,0.0000,0.0152,-0.0292,16,4.93,0.083333,5615.00

In [24]:
#df.to_csv('') if needed

In [23]:
df4.to_csv('df4_modified.csv',index=False)
df5.to_csv('df5_modified.csv',index=False)
df6.to_csv('df6_modified.csv',index=False)